openapi: 3.0.3
info:
  title: Popper
  description: Backend spec for popper app
  version: 1.0.0
servers:
  - url: 'https://popper-service.herokuapp.com/'
paths:
  /operator/sign_in:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
  /operator/sign_up:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
components:
  schemas:
    Token:
      properties:
        token:
          type: string
    Operator:
      properties:
        id:
          type: integer
        firstname:
          type: string
        second_name:
          type: string
        surname:
          type: string
        phone:
          type: integer
        password:
          type: string