openapi: 3.0.3
info:
  title: Popper
  description: Backend spec for popper app
  version: 0.0.1
servers:
  - url: 'https://popper-service.herokuapp.com/'
  - url: 'http://localhost:80'
  - url: 'https://webpanel.remcoil.space/'
paths:

  /bobbin:
    get:
      tags:
        - bobbin
      responses:
        '200':
          description: List of all bobbins
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfBobbins'

  /bobbin/{id}:
    get:
      tags:
        - bobbin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Bobbin information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bobbin'
        '400':
          description: Bobbin not found

  /bobbin/task/{id}:
    get:
      tags:
        - bobbin
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of bobbins of one task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfBobbins'

  /task:
    get:
      tags:
        - task
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfTasks'

    put:
      tags:
        - task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
        '400':
          description: Bad request

    post:
      tags:
        - task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskIdentity'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /task/{id}:
    get:
      tags:
        - task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task infromation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Task not found

    delete:
      tags:
        - task
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully

  /action:
    get:
      tags:
        - action
      responses:
        '200':
          description: List of actions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfActions'

    post:
      tags:
        - action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '400':
          description: Bad request
        '403':
          description: Action already exists
        '200':
          description: Action created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'
    put:
      tags:
        - action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action'
      responses:
        '200':
          description: Action update
        '400':
          description: Bad request

  /action/bobbin/{bobbin_id}:
    get:
      tags:
        - action
      parameters:
        - in: path
          name: bobbin_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Full list of one bobbin actions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfFullActions'

  /action/task/{task_id}:
    get:
      tags:
        - action
      parameters:
        - in: path
          name: task_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Full list of one task actions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfFullActions'

  /action/{id}:
    delete:
      tags:
        - action
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Action deleted successfully

  /operator?active_only=true:
    get:
      tags:
        - operator
      parameters:
        - in: query
          name: active_only
          schema:
            type: boolean
      responses:
        '200':
          description: List of operators
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfOperators'

  /operator/{id}:
    delete:
      tags:
        - operator
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Operator deleted successfully

  /operator/sign_in:
    post:
      tags:
        - operator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '401':
          description: Wrong password or phone
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'

  /operator/sign_up:
    post:
      tags:
        - operator
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Operator already exists

components:
  schemas:

    FullAction:
      properties:
        bobbin_id:
          type: integer
        bobbin_number:
          type: integer
        first_name:
          type: string
        second_name:
          type: string
        surname:
          type: string
        action_type:
          type: string
        done_time:
          type: string
        successful:
          type: boolean

    Action:
      properties:
        id:
          type: integer
        operator_id:
          type: integer
        bobbin_id:
          type: integer
        action_type:
          type: string
        done_time:
          type: string
        successful:
          type: boolean

    Token:
      properties:
        token:
          type: string

    FullTask:
      properties:
        id:
          type: integer
        task_name:
          type: string
        task_number:
          type: string
        quantity:
          type: integer
        winding:
          type: integer
        output:
          type: integer
        isolation:
          type: integer
        molding:
          type: integer
        crimping:
          type: integer
        quality:
          type: integer
        testing:
          type: integer

    Task:
      properties:
        id:
          type: integer
        task_name:
          type: string
        task_number:
          type: string
        quantity:
          type: integer

    Operator:
      properties:
        id:
          type: integer
        first_name:
          type: string
        second_name:
          type: string
        surname:
          type: string
        phone:
          type: string
        password:
          type: string
        active:
          type: boolean

    Bobbin:
      properties:
        id:
          type: integer
        task_id:
          type: integer
        bobbin_number:
          type: integer

    ListOfActions:
      type: array
      items:
        $ref: '#/components/schemas/Action'

    ListOfFullActions:
      type: array
      items:
        $ref: '#/components/schemas/FullAction'

    ListOfBobbins:
      type: array
      items:
        $ref: '#/components/schemas/Bobbin'

    ListOfOperators:
      type: array
      items:
        $ref: '#/components/schemas/Operator'

    ListOfTasks:
      type: array
      items:
        $ref: '#/components/schemas/Task'

    TaskIdentity:
      properties:
        task_name:
          type: string
        task_number:
          type: string
        quantity:
          type: integer

    Credentials:
      properties:
        phone:
          type: string
        password:
          type: string