openapi: 3.0.3
info:
  title: Popper
  description: Backend spec for popper app
  version: 0.0.1
servers:
  - url: 'https://popper-service.herokuapp.com/'
  - url: 'http://localhost:80'
paths:

  /task:
    get:
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfTasks'

  /task/delete/{task_name}:
    get:
      parameters:
        - in: path
          name: task_name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task deleted successfully

  /task/create:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskIdentity'
      responses:
        '200':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /operator/getAll:
    get:
      responses:
        '200':
          description: List of operators
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfOperators'

  /operator/sign_in:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'

  /operator/sign_up:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'

components:
  schemas:

    Token:
      properties:
        token:
          type: string

    Task:
      properties:
        id:
          type: integer
        task_name:
          type: string
        task_number:
          type: string
        quantity:
          type: integer
        winding:
          type: integer
        output:
          type: integer
        isolation:
          type: integer
        molding:
          type: integer
        crimpimng:
          type: integer
        quality:
          type: integer
        testing:
          type: integer

    Operator:
      properties:
        id:
          type: integer
        firstname:
          type: string
        second_name:
          type: string
        surname:
          type: string
        phone:
          type: string
        password:
          type: string

    ListOfOperators:
      type: array
      items:
        $ref: '#/components/schemas/Operator'

    ListOfTasks:
      type: array
      items:
        $ref: '#/components/schemas/Task'

    TaskIdentity:
      properties:
        task_name:
          type: string
        task_number:
          type: string
        quantity:
          type: integer

    Credentials:
      properties:
        phone:
          type: string
        password:
          type: string