version: "3.6"

services:
  popper:
    image: rem-coil.registry.jetbrains.space/p/popper/popper/myimage:latest
    environment:
      PORT: ${PORT}
      JDBC_DATABASE_PASSWORD: ${JDBC_PASSWORD}
      JDBC_DATABASE_USERNAME: ${JDBC_USERNAME}
      JDBC_DATABASE_URL: ${JDBC_URL}
      SECRET: ${JWT_SECRET}
    depends_on:
      - database
    ports:
      - "8080:80"

  database:
    image: postgres:11
    container_name: popper_database
    volumes:
      - popper_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  popper_db: